set global grepcmd "rg"
alias global rg grep

# set tabstop to 4
set global indentwidth 4 

#Setup tabs to spaces
map global insert <tab> '<a-;><gt>'
map global insert <backtab> '<a-;><lt>'

# Plugins
source "%val{config}/plugins/plug.kak/rc/plug.kak"
